sudo: required
dist: trusty
language: node_js
node_js: '10'
addons:
  apt:
    packages:
    - dpkg
    - google-chrome-stable
stages:
- name: Run All Tests
- name: Deploy to GCP
- name: Deploy release branch
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"
services:
- docker
before_deploy:
- python2 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL);
  fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null;
  fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components update kubectl
script:
- echo "skipping tests"
branches:
  only:
  - master
  - development
  - "/^release.*$/"
jobs:
  fast_finish: true
  include:
  - stage: Run All Tests
    script: "./deployment/files-for-travis/docker-run-all-tests.sh"
  - stage: Deploy to GCP
    deploy:
    - provider: script
      skip_cleanup: true
      script: "./deployment/files-for-travis/update-dev-cluster.sh"
      on:
        branch: development
  - stage: Deploy release branch
    deploy:
    - provider: script
      script: "./deployment/gcp/deploy-release.sh -m release -n ds"
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^release.*$"
before_install:
- openssl aes-256-cbc -K $encrypted_cd0109970fec_key -iv $encrypted_cd0109970fec_iv
  -in envs.tar.enc -out envs.tar -d
- tar xvf envs.tar
