FROM base_docker_image

RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list

RUN apt-get update

#get & install Ds-server
RUN mkdir /home/ds-server
WORKDIR /home/ds-server

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm i
RUN npm run update:p-queue

COPY ./common ./common
COPY ./server ./server
COPY ./credentials ./credentials
COPY ./deployment ./deployment

ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

ARG MODE_ENV
ENV MODE_ENV ${MODE_ENV}

RUN npm run build:server-puppeteer

EXPOSE 80 3000 5000

CMD ["npm", "run", "server-puppeteer"]
