FROM base_docker_image

RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list

RUN apt-get update

#get & install Ds-server
RUN mkdir /home/ds-cms
WORKDIR /home/ds-cms

COPY ./cms ./cms
COPY ./credentials ./credentials
COPY ./common ./common
COPY ./uploads ./uploads
COPY ./server ./server
COPY ./translations ./translations
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm i
RUN npm i webpack@3.12.0 -g
RUN npm run update:p-queue

ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

ARG MODE_ENV
ENV MODE_ENV ${MODE_ENV}

RUN npm run build:server
RUN npm run build:server-cms
RUN npm run build:client-cms

EXPOSE 443 3001 8080 80

CMD ["npm", "run", "server-cms"]

